"""Initial migration

Revision ID: 04dae2a5dc2d
Revises: 
Create Date: 2026-02-05 02:08:40.811953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dae2a5dc2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We must supply a server_default because existing rows need a value
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    
    # After the column is added, we can remove the server_default if we want, 
    # but keeping it is fine for boolean flags.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
